name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - users: actions/checkoutv@2
    - name: Run Django unit tests
      run: |
        pip3 install --user django
        python3 manage.py test